### PR TITLE
add color controls

### PR DESCRIPTION
**Pull request by peteshand**
Add support for setting k4a_device_set_color_control

This should resolve
https://github.com/wouterverweirder/kinect-azure/issues/9

### CODE REVIEW

**Comment by wouterverweirder** [comment]
Thanks for this new pull request!

I'd prefer again to stay a bit closer to the SDK api, and just expose the `k4a_device_set_color_control` method.

Something like this (not tested as not on windows machine right now):

```cpp
Napi::Value MethodSetColorControl(const Napi::CallbackInfo& info) {
  if (info.Length() < 0) {
    Napi::TypeError::New(env, "Wrong number of arguments")
        .ThrowAsJavaScriptException();
    return env.Null();
  }
  Napi::Object js_config =  info[0].As<Napi::Object>();
  Napi::Value js_command = js_config.Get("command");
  if (!js_command.IsNumber()) {
    Napi::TypeError::New(env, "missing command")
        .ThrowAsJavaScriptException();
    return env.Null();
  }
  k4a_color_control_command_t command = (k4a_color_control_command_t) js_command.As<Napi::Number>().Int32Value();

  Napi::Value js_mode = js_config.Get("mode");
  if (!js_mode.IsNumber()) {
    Napi::TypeError::New(env, "missing mode")
        .ThrowAsJavaScriptException();
    return env.Null();
  }
  k4a_color_control_mode_t mode = (k4a_color_control_mode_t) js_mode.As<Napi::Number>().Int32Value();

  Napi::Value js_value = js_config.Get("value");
  if (!js_value.IsNumber()) {
    Napi::TypeError::New(env, "missing value")
        .ThrowAsJavaScriptException();
    return env.Null();
  }
  int32_t value = (int32_t) js_value.As<Napi::Number>().Int32Value();
  k4a_device_set_color_control(g_device, command, mode, value);
  return info.Env().Undefined();
}
```

On the javascript side, we could duplicate the enums for the possible k4a_color_control_command_t  and k4a_color_control_mode_t values, like with the depth mode etc..

The javascript side could have both the setColorControl function as well as extra functions that call into the setColorControl function with the correct values:

```javascript
/**
 * Set the Azure Kinect color sensor control value.
 * @param {Object} options The configuration for the color control
 * @param {number} options.command Color sensor control command. (eg KinectAzure. K4A_COLOR_CONTROL_EXPOSURE_TIME_ABSOLUTE, ...)
 * @param {number} options.mode Color sensor control mode to set. This mode represents whether the command is in automatic or manual mode. (eg KinectAzure. K4A_COLOR_CONTROL_MODE_AUTO, KinectAzure.K4A_COLOR_CONTROL_MODE_MANUAL)
 * @param {number} options.value Value to set the color sensor's control to. The value is only valid if mode is set to K4A_COLOR_CONTROL_MODE_MANUAL, and is otherwise ignored.
*/
setColorControl(options) { return kinect.setColorControl(options) }

/**
 * Helper function to set the exposure
 */
setExposure(value) {
  this.setColorControl({command: KinectAzure.K4A_COLOR_CONTROL_EXPOSURE_TIME_ABSOLUTE, mode: KinectAzure.K4A_COLOR_CONTROL_MODE_MANUAL, value: 1});
}
```

**Comment by JpEncausse** [comment]
Hello, is it possible to merge / implement in master this solution or an other ?
Thanks !

**Comment by wouterverweirder** [comment]
made the adjustments to keep the C side simple and merged.

**Comment by wouterverweirder** [comment]
thanks for your work @peteshand !

**Pull request merged**
