### PR TITLE
Playback and cpp image processing

### PR DESCRIPTION
**Pull request by peteshand**
Hey @wouterverweirder 

This pull requests adds quite a few new features.
Let me know if you're not a fan of any of them or how they've been implemented.

Features:
* MKV playback api has been added. This allows you to record an MKV with the 'k4arecorder' tools in the Azure Kinect SDK. I've had to add an additional dll file to get this working.

* new config props: 'depth_to_greyscale' and 'depth_to_redblue' have been added and basically move the image processing / conversion to the cpp side.

* new config prop: 'apply_depth_to_alpha', when set to true will apply the depth greyscale to the alpha channel of the color image.

* synchronized_images_only api exposed.

* console.cc class added (before I saw your note about printf, which is actually all I was after)

### CODE REVIEW

**Comment by wouterverweirder** [comment]
Thanks for these enhancements! I'll play with it and review this weekend :-)

**Comment by peteshand** [comment]
Cool, obviously feel free to change or remove stuff.. for example I'm no longer using console.cc after your comment about cpp's printf method

**Comment by peteshand** [comment]
Cool, obviously feel free to change or remove stuff.. for example I'm no longer using console.cc after your comment about cpp's printf method.

**Comment by wouterverweirder** [comment]
merged & published as version 0.0.11, just moved the demo of the viewer as last one in the list and fixed a bug in my injected renderer script for the demos.

Thanks for your work!

**Pull request merged**
